[package]
name = "repl"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_core = "0.283.0"
rustpython-vm = { version = "0.3.1", features = ["importlib", "jit", "rustpython-jit", "threading", "vm-tracing-logging"] }
